/**
 * Drexel Pride Task
 */
var gutil = require('gulp-util');
var gulp = require('gulp');

var drexelDragon =
"\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMMMMMNMMMMMMMMMMNDDDDDDDDDDDDDDDDDDNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMMMNNNMMMMDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDNMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMNNNNNNDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD8NMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMNNNNNNNNDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMNNNZNNNNNNNDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDNMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMNNN+NN+NNN+NNDDDDDDDDDDDDDDDDDDNDDDDDDDDDDDDDDDDDDDDDDDDNMMMMMMMMMMMM\n" +
"MMMMMMMMMMNNNNNNN+NNNN+NN8DDDDNDDDDDNNDDDDNNDDDDDNDDDDDDDDDDDDDDDDDDDNMMMMMMMMMM\n" +
"MMMMMMMMDNNNNNNNN+NNNNNN+NDDDDZ?NDDN++NDDNN+NDDDDNDDDDDDDDDDDDDDDDDDDDDMMMMMMMMM\n" +
"MMMMMMMNNNNN+NNNN+NNNNNNN+NNDN++++N+++++NNON+NDDN+DDDDDDDDDDDDDDDDDDDDDDNMMMMMMM\n" +
"MMMMMNNNNNNNNNNNN+NNNNNNNNN++NNNNNN++++NNN++N+NN++N8DDDDDDDDDDDDDDDDDDDDDDMMMMMM\n" +
"MMMMNDNNNNN$NNNNN+NNNNNNNNNNN+++NNNNN++NN++++N++N++NDDDDDDDDDDDDDDDDDDDDDDDMMMMM\n" +
"MMMMDNNNNNNNNNNNN+NNNNNNNNN++++++++++++N+++NNNNN++N+N8DDDDDDDDDDDDDDDDDDDDDDMMMM\n" +
"MMMDNNNNNN+NNNNNN++NNNNN++++++++++++++++N++++NNN++D++INNNNDDDDDDDDDDDDDDDDDDNMMM\n" +
"MMDNNNNNNNONNNNNNN+NNNN++++++++NNNNNNNNNN++NN++++++++++NNNNNND8DNNDDDDDDDDDDDMMM\n" +
"MMDNNNNNNNNNNNNNNN++NN++++++NNNNNNNNNNNNN+N+NNNN?+++++++++++++N+NDDDDDDDNNDDDNMM\n" +
"MMNNNNNNNNNNNNNNNNN+NN+++++NNNNNNNNNZNN+N+N?NNN+++++N+++++++++N+DDDDDNOOOOONDDMM\n" +
"MNNNNNNNNNNNNNNNNNNN+N++++NN+NNN+ONN++NNNNDDDDN+++++++DDD.  .N+7DDDDNOOO8N8DDDMM\n" +
"MDNNNNNNNNNNNNNNNNNN+++++NNNN+NNN+++NNDDDDDDDDN+++++++NDDDDD.N:NDDDNOOONDDDDDDMM\n" +
"MNNNNNNNNN+NNNNNNN+++++++NNNNN++NNNDDDDDDDDDDDDD+++++++IZDDDD.DDDDNOOONDDDDDDDMM\n" +
"MNNNNNNNNN+NNNNNN+++++8NNNNNNNNNNNNNDDDDDDDDDDDDDNNN++++NDDDDDDNNNDNNNDDDDDDDDMM\n" +
"MMNNNNNNNNN+NNNNN++++++++++++++++++++++++++N8DDDDDDDDDN+++NNDDNN8DDDDDNN8NNDDNMM\n" +
"MMNNNNNNNNN+NNNNN++++++++++++++NNNNNNZ+NNNN+NDDDDDDDDDDN+++NDDNOOOOOOOOONDDDDMMM\n" +
"MMNNNNNNNNNN+NNNN++++++++NNNN$NNNNNNNNN+++++++NDDDDDDDDD++NDDDDDDDDN8OOODDDDNMMM\n" +
"MMNNNNNNNNNNN++NNNNNNNNNNN+NN+NN++++++NNDDN++NDDDDDDDDDNNDDDDDDNNND8DNOON8DDMMMM\n" +
"MMMNNNNNNNNNNN++NN+NNNNNNN+NNN+NNN++++NNDDN++DDDDDDDDDDDDDDDDDDDDOODDDDOONDMMMMM\n" +
"MMMNNNNNNNNNNNNN++NNNNNN+NNNNNNN+NNN+N++IN++NDDDDDDDDDDDDDDDDDDDDNONDDDDDNNNMMMM\n" +
"MMMMNNNNNNNNNNNNNNDDDNNNNNNDDDDNNN+NNN+NN+++NDDDDDDDDDDDDDDDDDDDDDDNNNDDDMMMMMMM\n" +
"MMMMMNNNNNNNNNNNNDDDDDDDDNDDDDDDDDNNNNN+++NNDDDDDDDDDDDDDDDDDDDDDDDDDDDMMMMMMMMM\n" +
"MMMMMMNNNNNNNNNNDDDDDDDDDDDDDDDDDDDDDNNNN+++NDDNNNNNDDDDDDDDDDDDDDDDDNMMMMMMMMMM\n" +
"MMMMMMMNNNNNNNNDDDDDDDDDDDDDDDDDDDDDDDDNNN++++++7N?++N+NDDDDDDDDDDDDMMMMMMMMMMMM\n" +
"MMMMMMMMNNNNNNNDDDDDDDDDDDDDDDDDDDDDDDDD+++++++++++N++N++N8DDDDDDNMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMNNNNNMNDDDDDDDDDDDDDDDDDDDDDDD8+++++++++++N+?NN+DDD8DMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMNNNNMMMMNDDDDDDDDDDDDDDDDDDDDDNNNNNNDDNNNNNDDNDDNMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMNNMMMMMMMMMDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDNMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMNMMMMMMMMMMMMMNNDDDDDDDDDDDDDDDDDDNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM TEAM DIGGLY MM\n" +
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM";

gulp.task('drexel', function() {
   gutil.log(gutil.colors.yellow(drexelDragon));
});
